version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: dreams-db
    environment:
      POSTGRES_DB: dreams
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
